[platformio]
default_envs = m5stack-e2e
[env:m5stack-e2e]
platform = espressif32@6.12.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags = -std=gnu++11 -fno-exceptions
build_flags =
    -std=gnu++17
    -fexceptions
    -D VLP_E2E_TEST_ONLY=1
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_MBEDTLS_HKDF_C=1
    -D CONFIG_MBEDTLS_RIPEMD160_C=1
extra_scripts = pre:scripts/mbedtls.py
